#ifndef PICOPAL_SLOT
#define PICOPAL_SLOT 3
#endif

#define PICOPAL_REGISTER(n) (*(volatile unsigned char *)(0xc080 | (n) | (PICOPAL_SLOT << 4)))

#define PICOPAL_WRDATA    PICOPAL_REGISTER(0x0)
#define PICOPAL_ALSB      PICOPAL_REGISTER(0x1)
#define PICOPAL_AMSB      PICOPAL_REGISTER(0x2)
#define PICOPAL_MODE      PICOPAL_REGISTER(0x3)
#define PICOPAL_TBCOLOR   PICOPAL_REGISTER(0x4)
#define PICOPAL_BORDER    PICOPAL_REGISTER(0x5)
#define PICOPAL_RDDATA    PICOPAL_REGISTER(0x7)
#define PICOPAL_WRFONT    PICOPAL_REGISTER(0x8)
#define PICOPAL_RDFONT    PICOPAL_REGISTER(0xf)
